### ISSUE TITLE
Diagram: Meta Issue 2

### ISSUE THREAD

**Issue by slisson** [JetBrains/MPS-extensions#120]
- [ ] #115 | Diagram Editor: sub-diagrams do not fill available space
- [ ] #114 | Diagram Editor: edges to parent box are attached on the wrong side of the port shape
- [ ] #113 | Diagram Editor: provide option to display the diagram pane in a separate window
- [ ] #112 | Diagram Editor: Improve support for cross-navigation
- [ ] #111 | Diagram Editor: significantly improve performance
- [ ] #110 | Diagram Editor: Support bidirectional edges
- [ ] #109 | Diagram Editor: Make the diagram pane fill the editor tab correctly when “fullscreen” is enabled
- [ ] #108 | Diagram Editor: Reset origin (top-left corner) on load/shrink
- [ ] #107 | Diagram Editor: provide option to enable manuel resizing of root diagram pane
- [ ] #106 | Diagram Editor: root diagram pane does not always update size correctly
- [ ] #105 | Diagram Editor: remove need for redundant editor definitions
- [ ] #104 | Diagram Editor: Having multiple palettes for one Diagram is problematic
- [ ] #103 | Diagram Editor: API to customize diagram buttons
- [ ] #102 | Diagram Editor: API to handle relocation of elements
- [ ] #101 | Diagram Editor: API to specify SNode for element in generic edge/box query
- [ ] #100 | Diagram Editor: switching into “edit mode” for embedded mps text editor does not work reliably
- [ ] #99 | Diagram Editor: zoom is inverted for regular mouse with scroll wheel
- [ ] #98 | Diagram Editor: support manual reordering / relocation of ports
- [ ] #97 | Diagram Editor: support orthogonal routing of “incoming” and “outgoing” edges
- [ ] #96 | Diagram Editor: calculation of box size does not consider contained edges
- [ ] #95 | Diagram Editor: add option for autolayout-on-changes
- [ ] #92 | Diagrams: Buttons overlap with content
- [ ] #91 | Diagrams: Boxes can be moved out of nested diagrams
- [ ] #90 | Subdiagrams are outside their box after autolayout and zoom
- [ ] #89 | Diagram: Add padding for boxes on auto-size
- [ ] #88 | Diagram: Support copy & paste
- [ ] #87 | Finish merging diagram palette and context actions
- [ ] #86 | When cloning a model with a graphical editor, layout is not preserved
- [ ] #85 | Toolbar does not always show completely
- [ ] #84 | Text within diagram box does not always update in time
- [ ] #83 | Deleting a node reference in diagram editor reinstitues old reference instead of deleting it
- [ ] #82 | Auto layout option moves the contents of boxes (it should not)
- [ ] #81 | Borders inside boxes don't work correctly.
- [ ] #80 | Diagram: Meta Issue
- [ ] #79 | Diagram: Allow shapes to reserve additional space
- [ ] #78 | Should be able to adjust spacing/padding of box contents.
- [ ] #77 | Selection and navigation in diagrams is unexpected
- [ ] #76 | Diagram: Set focus to the editor after drop from palette
- [ ] #75 | Drag & Drop features for the graphical editor
- [ ] #74 | Colors in diagram editor definition not legible
- [ ] #73 | Diagram: Loop edges cannot be layouted
- [ ] #72 | Boxes from a subdiagram can be dragged outside of the diagram over the upper or left boundary line
- [ ] #71 | Boxes from a subdiagram can be dragged outside of the diagram over the upper or left boundary line
- [ ] #70 | Connection edges drawn over ports make the ports hard to select
- [ ] #69 | Mouse cursor always has a move icon over diagram nodes (on Win platform)
- [ ] #68 | Compilation error in port definition
- [ ] #67 | Refactoring (extract method) raises exception inside shape definitions
- [ ] #66 | Connection in graphical should draw crossings properly
- [ ] #65 | Allow to specify read-only in nodesQeury
- [ ] #64 | Code generated for "if" in shape property results in cast error
- [ ] #63 | Support automatic resizing of diagram pane to make sure that diagram content can be fully seen
- [ ] #62 | Diagram: Palette doesn't work in floating mode
- [ ] #61 | Styles border-size/border-color don't work in zoomed diagrams
- [ ] #60 | diagram language does not reexport diagram.runtime solution
- [ ] #59 | Find (CMD+F) loses focus when diagram was active
- [ ] #58 | Enable masking/unmasking of edges in diagrams based on generic box/edge queries
- [ ] #57 | Automatically fit to size all new boxes placed on diagrams
- [ ] #56 | Enable masking/unmasking of edges in diagrams based on generic box/edge queries
- [ ] #55 | Missing information in graphical projection of a composite block
- [ ] #54 | Diagram Editor: view of a nested querylist editor is not updated when selecting a reference from completion menu
- [ ] #53 | Diagram Editor: Upon auto-layout, edges get surprising shapes and labels are not correctly repositioned to their respective edges
- [ ] #52 | Diagram Editor: Self-to-self edge becomes zero-length and unchangeable
- [ ] #51 | Diagram Editor: Add a "starting box" concept to layout specification in a diagram
- [ ] #50 | Diagram Editor: Searching for text in a diagram starts renaming elements
- [ ] #49 | Diagram Editor: print editor button does not produce a result when a diagram is present
- [ ] #48 | Focus when leaving edit box
